# Site settings
title: Riccardo De Zen
description: "Computer Engineering Student"

# Actual base url of the website
url: "https://ricdezen.github.io"
# Base url
baseurl: "/"

# Author information
author:
  name: "Riccardo De Zen"
  email: "riccardodezen98@gmail.com"
  url: "https://ricdezen.github.io"

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Markdown
markdown: kramdown